"""empty message

Revision ID: 0d91a76a4fef
Revises: e2ee47d8706e
Create Date: 2024-07-20 16:39:22.050595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d91a76a4fef'
down_revision = 'e2ee47d8706e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('methods_payment', sa.String(length=120), nullable=False),
    sa.Column('payment_date', sa.String(length=120), nullable=False),
    sa.Column('total', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methods_payment'),
    sa.UniqueConstraint('payment_date'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('total'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=120), nullable=False),
    sa.Column('course_id', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('quantity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_table('courses')
    # ### end Alembic commands ###
