"""empty message

Revision ID: d9a111a34eb1
Revises: 0d91a76a4fef
Create Date: 2024-07-22 17:15:38.982558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a111a34eb1'
down_revision = '0d91a76a4fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methods_payment', sa.String(length=120), nullable=False),
    sa.Column('payment_date', sa.String(length=120), nullable=False),
    sa.Column('total', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methods_payment'),
    sa.UniqueConstraint('payment_date'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('total')
    )
    op.drop_table('order')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('order_item_course_id_key', type_='unique')
        batch_op.drop_constraint('order_item_order_id_key', type_='unique')
        batch_op.drop_constraint('order_item_quantity_key', type_='unique')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('order_item_quantity_key', ['quantity'])
        batch_op.create_unique_constraint('order_item_order_id_key', ['order_id'])
        batch_op.create_unique_constraint('order_item_course_id_key', ['course_id'])
        batch_op.alter_column('order_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('methods_payment', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('total', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='order_pkey'),
    sa.UniqueConstraint('methods_payment', name='order_methods_payment_key'),
    sa.UniqueConstraint('payment_date', name='order_payment_date_key'),
    sa.UniqueConstraint('status', name='order_status_key'),
    sa.UniqueConstraint('total', name='order_total_key'),
    sa.UniqueConstraint('user_id', name='order_user_id_key')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
